# Generated by Django 5.2.10 on 2026-01-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bottom_len',
            new_name='bottom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='top_len',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top',
            field=models.FloatField(blank=True, help_text='Top length with ', null=True),
        ),
    ]
