# Generated by Django 5.2.10 on 2026-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_bottom_len_userprofile_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bottom',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='top',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=3, null=True),
        ),
    ]
