# Generated by Django 5.2.10 on 2026-01-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imageupload_detected_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
