# Generated by Django 5.2.10 on 2026-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='market_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='market_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='source',
            field=models.CharField(choices=[('AMAZON', 'Amazon'), ('TEMU', 'Temu'), ('TRENDYOL', 'Trendyol'), ('LOCAL', 'Local Market')], default='AMAZON', max_length=20),
        ),
    ]
