# Generated by Django 5.2.10 on 2026-01-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imageupload_market_location_imageupload_market_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='detected_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
